/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{email_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Email
         * @description Fetch email data for a specific email type
         */
        get: operations["fetch_email_emails__email_type__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/emails/{email_type}/render": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render Email
         * @description Render email data to HTML using the appropriate template
         */
        post: operations["render_email_emails__email_type__render_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Advert */
        Advert: {
            /** Url */
            url: string;
            /** Image Url */
            image_url: string;
        };
        /** BEEmailData */
        BEEmailData: {
            top_image: components["schemas"]["TopImage"];
            /** Tides */
            tides: string;
            /** Weather */
            weather: string;
            /** Date */
            date: string;
            /** News Stories */
            news_stories: components["schemas"]["NewsStory"][];
            /** Horizontal Adverts */
            horizontal_adverts: components["schemas"]["Advert"][];
            /** Vertical Adverts */
            vertical_adverts: components["schemas"]["Advert"][];
            /** Sports Stories */
            sports_stories: components["schemas"]["NewsStory"][];
            /** Business Stories */
            business_stories: components["schemas"]["NewsStory"][];
            /** Connect Image Url */
            connect_image_url: string;
            /** Community Stories */
            community_stories: components["schemas"]["NewsStory"][];
            /** Podcast Stories */
            podcast_stories: components["schemas"]["NewsStory"][];
            /** Family Notices */
            family_notices: components["schemas"]["FamilyNotice"][];
        };
        /**
         * EmailType
         * @enum {string}
         */
        EmailType: "be" | "ge" | "jep";
        /** FamilyNotice */
        FamilyNotice: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Funeral Director */
            funeral_director?: string | null;
            /** Additional Text */
            additional_text?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewsStory */
        NewsStory: {
            /** Headline */
            headline: string;
            /** Text */
            text: string;
            /**
             * Date
             * Format: date-time
             */
            date: string;
            /** Author */
            author: string;
            /** Url */
            url: string;
            /** Image Url */
            image_url: string;
        };
        /** TopImage */
        TopImage: {
            /** Url */
            url: string;
            /** Image Url */
            image_url: string;
            /** Author */
            author?: string | null;
            /** Text */
            text?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    fetch_email_emails__email_type__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email_type: components["schemas"]["EmailType"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BEEmailData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_email_emails__email_type__render_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email_type: components["schemas"]["EmailType"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BEEmailData"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
